#!/bin/bash

cp -a ADBOS/* /usr/local/share/perl/5.10.1/ADBOS/
install -m 755 process.pl /usr/local/opdef/
install -m 755 serial-dump.pl /usr/local/opdef/
install -m 755 testparse.pl /usr/local/opdef/
